<?php
/**
 * Regenerate locales.json with ALL Google Translate languages
 * and currencies.json with exactly 135 Stripe currencies
 */

// 188 Google Translate NMT languages
$languages = [
    ['code' => 'ab', 'name' => 'Abkhaz', 'native' => 'Аԥсуа'],
    ['code' => 'ace', 'name' => 'Acehnese', 'native' => 'Bahsa Acèh'],
    ['code' => 'ach', 'name' => 'Acholi', 'native' => 'Lwo'],
    ['code' => 'af', 'name' => 'Afrikaans', 'native' => 'Afrikaans'],
    ['code' => 'sq', 'name' => 'Albanian', 'native' => 'Shqip'],
    ['code' => 'alz', 'name' => 'Alur', 'native' => 'Dhu Alur'],
    ['code' => 'am', 'name' => 'Amharic', 'native' => 'አማርኛ'],
    ['code' => 'ar', 'name' => 'Arabic', 'native' => 'العربية', 'rtl' => true],
    ['code' => 'hy', 'name' => 'Armenian', 'native' => 'Հայdelays?'],
    ['code' => 'as', 'name' => 'Assamese', 'native' => 'অসমীয়া'],
    ['code' => 'awa', 'name' => 'Awadhi', 'native' => 'अवधी'],
    ['code' => 'ay', 'name' => 'Aymara', 'native' => 'Aymar'],
    ['code' => 'az', 'name' => 'Azerbaijani', 'native' => 'Azərbaycan'],
    ['code' => 'ban', 'name' => 'Balinese', 'native' => 'Basa Bali'],
    ['code' => 'bm', 'name' => 'Bambara', 'native' => 'Bamanankan'],
    ['code' => 'ba', 'name' => 'Bashkir', 'native' => 'Башҡортса'],
    ['code' => 'eu', 'name' => 'Basque', 'native' => 'Euskara'],
    ['code' => 'btx', 'name' => 'Batak Karo', 'native' => 'Batak Karo'],
    ['code' => 'bts', 'name' => 'Batak Simalungun', 'native' => 'Batak Simalungun'],
    ['code' => 'bbc', 'name' => 'Batak Toba', 'native' => 'Batak Toba'],
    ['code' => 'be', 'name' => 'Belarusian', 'native' => 'Беларуская'],
    ['code' => 'bem', 'name' => 'Bemba', 'native' => 'Chibemba'],
    ['code' => 'bn', 'name' => 'Bengali', 'native' => 'বাংলা'],
    ['code' => 'bew', 'name' => 'Betawi', 'native' => 'Betawi'],
    ['code' => 'bho', 'name' => 'Bhojpuri', 'native' => 'भोजপুরী'],
    ['code' => 'bik', 'name' => 'Bikol', 'native' => 'Bikol'],
    ['code' => 'bs', 'name' => 'Bosnian', 'native' => 'Bosanski'],
    ['code' => 'br', 'name' => 'Breton', 'native' => 'Brezhoneg'],
    ['code' => 'bg', 'name' => 'Bulgarian', 'native' => 'Български'],
    ['code' => 'bua', 'name' => 'Buryat', 'native' => 'Буряад'],
    ['code' => 'yue', 'name' => 'Cantonese', 'native' => '粵語'],
    ['code' => 'ca', 'name' => 'Catalan', 'native' => 'Català'],
    ['code' => 'ceb', 'name' => 'Cebuano', 'native' => 'Cebuano'],
    ['code' => 'ny', 'name' => 'Chichewa', 'native' => 'Chichewa'],
    ['code' => 'zh-CN', 'name' => 'Chinese Simplified', 'native' => '简体中文'],
    ['code' => 'zh-TW', 'name' => 'Chinese Traditional', 'native' => '繁體中文'],
    ['code' => 'cv', 'name' => 'Chuvash', 'native' => 'Чӑвашла'],
    ['code' => 'co', 'name' => 'Corsican', 'native' => 'Corsu'],
    ['code' => 'crh', 'name' => 'Crimean Tatar', 'native' => 'Qırımtatarca'],
    ['code' => 'hr', 'name' => 'Croatian', 'native' => 'Hrvatski'],
    ['code' => 'cs', 'name' => 'Czech', 'native' => 'Čeština'],
    ['code' => 'da', 'name' => 'Danish', 'native' => 'Dansk'],
    ['code' => 'din', 'name' => 'Dinka', 'native' => 'Thuɔŋjäŋ'],
    ['code' => 'dv', 'name' => 'Divehi', 'native' => 'ދިވެހި', 'rtl' => true],
    ['code' => 'doi', 'name' => 'Dogri', 'native' => 'डोगरी'],
    ['code' => 'dov', 'name' => 'Dombe', 'native' => 'Dombe'],
    ['code' => 'nl', 'name' => 'Dutch', 'native' => 'Nederlands'],
    ['code' => 'dz', 'name' => 'Dzongkha', 'native' => 'རྫོང་ཁ'],
    ['code' => 'en', 'name' => 'English', 'native' => 'English'],
    ['code' => 'eo', 'name' => 'Esperanto', 'native' => 'Esperanto'],
    ['code' => 'et', 'name' => 'Estonian', 'native' => 'Eesti'],
    ['code' => 'ee', 'name' => 'Ewe', 'native' => 'Eʋegbe'],
    ['code' => 'fj', 'name' => 'Fijian', 'native' => 'Vosa Vakaviti'],
    ['code' => 'fil', 'name' => 'Filipino', 'native' => 'Filipino'],
    ['code' => 'fi', 'name' => 'Finnish', 'native' => 'Suomi'],
    ['code' => 'fr', 'name' => 'French', 'native' => 'Français'],
    ['code' => 'fy', 'name' => 'Frisian', 'native' => 'Frysk'],
    ['code' => 'ff', 'name' => 'Fulani', 'native' => 'Fulfulde'],
    ['code' => 'gaa', 'name' => 'Ga', 'native' => 'Gã'],
    ['code' => 'gl', 'name' => 'Galician', 'native' => 'Galego'],
    ['code' => 'lg', 'name' => 'Ganda', 'native' => 'Luganda'],
    ['code' => 'ka', 'name' => 'Georgian', 'native' => 'ქართული'],
    ['code' => 'de', 'name' => 'German', 'native' => 'Deutsch'],
    ['code' => 'el', 'name' => 'Greek', 'native' => 'Ελληνικά'],
    ['code' => 'gn', 'name' => 'Guarani', 'native' => 'Avañeẽ'],
    ['code' => 'gu', 'name' => 'Gujarati', 'native' => 'ગુજરાતી'],
    ['code' => 'ht', 'name' => 'Haitian Creole', 'native' => 'Kreyòl Ayisyen'],
    ['code' => 'cnh', 'name' => 'Hakha Chin', 'native' => 'Lai Holh'],
    ['code' => 'ha', 'name' => 'Hausa', 'native' => 'Hausa'],
    ['code' => 'haw', 'name' => 'Hawaiian', 'native' => 'ʻŌlelo Hawaiʻi'],
    ['code' => 'he', 'name' => 'Hebrew', 'native' => 'עברית', 'rtl' => true],
    ['code' => 'hil', 'name' => 'Hiligaynon', 'native' => 'Ilonggo'],
    ['code' => 'hi', 'name' => 'Hindi', 'native' => 'हिन्दी'],
    ['code' => 'hmn', 'name' => 'Hmong', 'native' => 'Hmoob'],
    ['code' => 'hu', 'name' => 'Hungarian', 'native' => 'Magyar'],
    ['code' => 'hrx', 'name' => 'Hunsrik', 'native' => 'Hunsrückisch'],
    ['code' => 'is', 'name' => 'Icelandic', 'native' => 'Íslenska'],
    ['code' => 'ig', 'name' => 'Igbo', 'native' => 'Igbo'],
    ['code' => 'ilo', 'name' => 'Ilocano', 'native' => 'Ilokano'],
    ['code' => 'id', 'name' => 'Indonesian', 'native' => 'Bahasa Indonesia'],
    ['code' => 'ga', 'name' => 'Irish', 'native' => 'Gaeilge'],
    ['code' => 'it', 'name' => 'Italian', 'native' => 'Italiano'],
    ['code' => 'ja', 'name' => 'Japanese', 'native' => '日本語'],
    ['code' => 'jv', 'name' => 'Javanese', 'native' => 'Basa Jawa'],
    ['code' => 'kn', 'name' => 'Kannada', 'native' => 'ಕನ್ನಡ'],
    ['code' => 'pam', 'name' => 'Kapampangan', 'native' => 'Kapampangan'],
    ['code' => 'kk', 'name' => 'Kazakh', 'native' => 'Қазақша'],
    ['code' => 'km', 'name' => 'Khmer', 'native' => 'ភាសាខ្មែរ'],
    ['code' => 'cgg', 'name' => 'Kiga', 'native' => 'Rukiga'],
    ['code' => 'rw', 'name' => 'Kinyarwanda', 'native' => 'Ikinyarwanda'],
    ['code' => 'ktu', 'name' => 'Kituba', 'native' => 'Kikongo'],
    ['code' => 'gom', 'name' => 'Konkani', 'native' => 'कोंकणी'],
    ['code' => 'ko', 'name' => 'Korean', 'native' => '한국어'],
    ['code' => 'kri', 'name' => 'Krio', 'native' => 'Krio'],
    ['code' => 'ku', 'name' => 'Kurdish Kurmanji', 'native' => 'Kurdî'],
    ['code' => 'ckb', 'name' => 'Kurdish Sorani', 'native' => 'سۆرانی', 'rtl' => true],
    ['code' => 'ky', 'name' => 'Kyrgyz', 'native' => 'Кыргызча'],
    ['code' => 'lo', 'name' => 'Lao', 'native' => 'ລາວ'],
    ['code' => 'ltg', 'name' => 'Latgalian', 'native' => 'Latgaļu'],
    ['code' => 'la', 'name' => 'Latin', 'native' => 'Latina'],
    ['code' => 'lv', 'name' => 'Latvian', 'native' => 'Latviešu'],
    ['code' => 'lij', 'name' => 'Ligurian', 'native' => 'Ligure'],
    ['code' => 'li', 'name' => 'Limburgish', 'native' => 'Limburgs'],
    ['code' => 'ln', 'name' => 'Lingala', 'native' => 'Lingála'],
    ['code' => 'lt', 'name' => 'Lithuanian', 'native' => 'Lietuvių'],
    ['code' => 'lmo', 'name' => 'Lombard', 'native' => 'Lombard'],
    ['code' => 'luo', 'name' => 'Luo', 'native' => 'Dholuo'],
    ['code' => 'lb', 'name' => 'Luxembourgish', 'native' => 'Lëtzebuergesch'],
    ['code' => 'mk', 'name' => 'Macedonian', 'native' => 'Македонски'],
    ['code' => 'mai', 'name' => 'Maithili', 'native' => 'मैथिली'],
    ['code' => 'mak', 'name' => 'Makassar', 'native' => 'Basa Mangkasara'],
    ['code' => 'mg', 'name' => 'Malagasy', 'native' => 'Malagasy'],
    ['code' => 'ms', 'name' => 'Malay', 'native' => 'Bahasa Melayu'],
    ['code' => 'ml', 'name' => 'Malayalam', 'native' => 'മലയാളം'],
    ['code' => 'mt', 'name' => 'Maltese', 'native' => 'Malti'],
    ['code' => 'mi', 'name' => 'Maori', 'native' => 'Te Reo Māori'],
    ['code' => 'mr', 'name' => 'Marathi', 'native' => 'मराठी'],
    ['code' => 'chm', 'name' => 'Meadow Mari', 'native' => 'Олык марий'],
    ['code' => 'mni-Mtei', 'name' => 'Meiteilon', 'native' => 'ꯃꯤꯇꯩꯂꯣꯟ'],
    ['code' => 'min', 'name' => 'Minangkabau', 'native' => 'Baso Minang'],
    ['code' => 'lus', 'name' => 'Mizo', 'native' => 'Mizo ṭawng'],
    ['code' => 'mn', 'name' => 'Mongolian', 'native' => 'Монгол'],
    ['code' => 'my', 'name' => 'Myanmar', 'native' => 'မြန်မာ'],
    ['code' => 'nr', 'name' => 'Ndebele South', 'native' => 'isiNdebele'],
    ['code' => 'new', 'name' => 'Nepalbhasa', 'native' => 'नेपालभाषा'],
    ['code' => 'ne', 'name' => 'Nepali', 'native' => 'नेपाली'],
    ['code' => 'nso', 'name' => 'Northern Sotho', 'native' => 'Sepedi'],
    ['code' => 'no', 'name' => 'Norwegian', 'native' => 'Norsk'],
    ['code' => 'nus', 'name' => 'Nuer', 'native' => 'Thok Naath'],
    ['code' => 'oc', 'name' => 'Occitan', 'native' => 'Occitan'],
    ['code' => 'or', 'name' => 'Odia', 'native' => 'ଓଡ଼ିଆ'],
    ['code' => 'om', 'name' => 'Oromo', 'native' => 'Afaan Oromoo'],
    ['code' => 'pag', 'name' => 'Pangasinan', 'native' => 'Pangasinan'],
    ['code' => 'pap', 'name' => 'Papiamento', 'native' => 'Papiamentu'],
    ['code' => 'ps', 'name' => 'Pashto', 'native' => 'پښتو', 'rtl' => true],
    ['code' => 'fa', 'name' => 'Persian', 'native' => 'فارسی', 'rtl' => true],
    ['code' => 'pl', 'name' => 'Polish', 'native' => 'Polski'],
    ['code' => 'pt', 'name' => 'Portuguese', 'native' => 'Português'],
    ['code' => 'pa', 'name' => 'Punjabi', 'native' => 'ਪੰਜਾਬੀ'],
    ['code' => 'qu', 'name' => 'Quechua', 'native' => 'Runasimi'],
    ['code' => 'rom', 'name' => 'Romani', 'native' => 'Romani'],
    ['code' => 'ro', 'name' => 'Romanian', 'native' => 'Română'],
    ['code' => 'rn', 'name' => 'Rundi', 'native' => 'Ikirundi'],
    ['code' => 'ru', 'name' => 'Russian', 'native' => 'Русский'],
    ['code' => 'sm', 'name' => 'Samoan', 'native' => 'Gagana Samoa'],
    ['code' => 'sg', 'name' => 'Sango', 'native' => 'Sängö'],
    ['code' => 'sa', 'name' => 'Sanskrit', 'native' => 'संस्कृतम्'],
    ['code' => 'gd', 'name' => 'Scots Gaelic', 'native' => 'Gàidhlig'],
    ['code' => 'sr', 'name' => 'Serbian', 'native' => 'Српски'],
    ['code' => 'st', 'name' => 'Sesotho', 'native' => 'Sesotho'],
    ['code' => 'crs', 'name' => 'Seychellois Creole', 'native' => 'Seselwa'],
    ['code' => 'shn', 'name' => 'Shan', 'native' => 'လိၵ်ႈတႆး'],
    ['code' => 'sn', 'name' => 'Shona', 'native' => 'ChiShona'],
    ['code' => 'scn', 'name' => 'Sicilian', 'native' => 'Sicilianu'],
    ['code' => 'szl', 'name' => 'Silesian', 'native' => 'Ślōnsko godka'],
    ['code' => 'sd', 'name' => 'Sindhi', 'native' => 'سنڌي', 'rtl' => true],
    ['code' => 'si', 'name' => 'Sinhala', 'native' => 'සිංහල'],
    ['code' => 'sk', 'name' => 'Slovak', 'native' => 'Slovenčina'],
    ['code' => 'sl', 'name' => 'Slovenian', 'native' => 'Slovenščina'],
    ['code' => 'so', 'name' => 'Somali', 'native' => 'Soomaali'],
    ['code' => 'es', 'name' => 'Spanish', 'native' => 'Español'],
    ['code' => 'su', 'name' => 'Sundanese', 'native' => 'Basa Sunda'],
    ['code' => 'sw', 'name' => 'Swahili', 'native' => 'Kiswahili'],
    ['code' => 'ss', 'name' => 'Swati', 'native' => 'SiSwati'],
    ['code' => 'sv', 'name' => 'Swedish', 'native' => 'Svenska'],
    ['code' => 'tg', 'name' => 'Tajik', 'native' => 'Тоҷикӣ'],
    ['code' => 'ta', 'name' => 'Tamil', 'native' => 'தமிழ்'],
    ['code' => 'tt', 'name' => 'Tatar', 'native' => 'Татарча'],
    ['code' => 'te', 'name' => 'Telugu', 'native' => 'తెలుగు'],
    ['code' => 'tet', 'name' => 'Tetum', 'native' => 'Tetun'],
    ['code' => 'th', 'name' => 'Thai', 'native' => 'ไทย'],
    ['code' => 'ti', 'name' => 'Tigrinya', 'native' => 'ትግርኛ'],
    ['code' => 'ts', 'name' => 'Tsonga', 'native' => 'Xitsonga'],
    ['code' => 'tn', 'name' => 'Tswana', 'native' => 'Setswana'],
    ['code' => 'tr', 'name' => 'Turkish', 'native' => 'Türkçe'],
    ['code' => 'tk', 'name' => 'Turkmen', 'native' => 'Türkmençe'],
    ['code' => 'ak', 'name' => 'Twi', 'native' => 'Twi'],
    ['code' => 'uk', 'name' => 'Ukrainian', 'native' => 'Українська'],
    ['code' => 'ur', 'name' => 'Urdu', 'native' => 'اردو', 'rtl' => true],
    ['code' => 'ug', 'name' => 'Uyghur', 'native' => 'ئۇيغۇرچە', 'rtl' => true],
    ['code' => 'uz', 'name' => 'Uzbek', 'native' => 'Oʻzbekcha'],
    ['code' => 'vi', 'name' => 'Vietnamese', 'native' => 'Tiếng Việt'],
    ['code' => 'cy', 'name' => 'Welsh', 'native' => 'Cymraeg'],
    ['code' => 'xh', 'name' => 'Xhosa', 'native' => 'isiXhosa'],
    ['code' => 'yi', 'name' => 'Yiddish', 'native' => 'ייִדיש', 'rtl' => true],
    ['code' => 'yo', 'name' => 'Yoruba', 'native' => 'Yorùbá'],
    ['code' => 'yua', 'name' => 'Yucatec Maya', 'native' => 'Màaya Tʼàan'],
    ['code' => 'zu', 'name' => 'Zulu', 'native' => 'isiZulu']
];

// Build locales array
$locales = [];
foreach ($languages as $lang) {
    $locales[] = [
        'code' => $lang['code'],
        'language_code' => $lang['code'],
        'language_name' => $lang['name'],
        'language_native' => $lang['native'],
        'rtl' => $lang['rtl'] ?? false
    ];
}

$localesData = [
    'meta' => [
        'description' => 'All ' . count($locales) . ' Google Translate supported languages',
        'source' => 'Google Cloud Translation API NMT',
        'last_updated' => date('Y-m-d')
    ],
    'locales' => $locales
];

file_put_contents(__DIR__ . '/locales.json', json_encode($localesData, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
echo "Created locales.json with " . count($locales) . " languages\n";

// 135 Stripe currencies
$currencies = [
    ['code' => 'AED', 'name' => 'UAE Dirham', 'symbol' => 'د.إ', 'decimals' => 2],
    ['code' => 'AFN', 'name' => 'Afghan Afghani', 'symbol' => '؋', 'decimals' => 2],
    ['code' => 'ALL', 'name' => 'Albanian Lek', 'symbol' => 'L', 'decimals' => 2],
    ['code' => 'AMD', 'name' => 'Armenian Dram', 'symbol' => '֏', 'decimals' => 2],
    ['code' => 'ANG', 'name' => 'Netherlands Antillean Guilder', 'symbol' => 'ƒ', 'decimals' => 2],
    ['code' => 'AOA', 'name' => 'Angolan Kwanza', 'symbol' => 'Kz', 'decimals' => 2],
    ['code' => 'ARS', 'name' => 'Argentine Peso', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'AUD', 'name' => 'Australian Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'AWG', 'name' => 'Aruban Florin', 'symbol' => 'ƒ', 'decimals' => 2],
    ['code' => 'AZN', 'name' => 'Azerbaijani Manat', 'symbol' => '₼', 'decimals' => 2],
    ['code' => 'BAM', 'name' => 'Bosnia-Herzegovina Mark', 'symbol' => 'KM', 'decimals' => 2],
    ['code' => 'BBD', 'name' => 'Barbadian Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'BDT', 'name' => 'Bangladeshi Taka', 'symbol' => '৳', 'decimals' => 2],
    ['code' => 'BGN', 'name' => 'Bulgarian Lev', 'symbol' => 'лв', 'decimals' => 2],
    ['code' => 'BIF', 'name' => 'Burundian Franc', 'symbol' => 'FBu', 'decimals' => 0],
    ['code' => 'BMD', 'name' => 'Bermudan Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'BND', 'name' => 'Brunei Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'BOB', 'name' => 'Bolivian Boliviano', 'symbol' => 'Bs.', 'decimals' => 2],
    ['code' => 'BRL', 'name' => 'Brazilian Real', 'symbol' => 'R$', 'decimals' => 2],
    ['code' => 'BSD', 'name' => 'Bahamian Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'BWP', 'name' => 'Botswanan Pula', 'symbol' => 'P', 'decimals' => 2],
    ['code' => 'BYN', 'name' => 'Belarusian Ruble', 'symbol' => 'Br', 'decimals' => 2],
    ['code' => 'BZD', 'name' => 'Belize Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'CDF', 'name' => 'Congolese Franc', 'symbol' => 'FC', 'decimals' => 2],
    ['code' => 'CHF', 'name' => 'Swiss Franc', 'symbol' => 'CHF', 'decimals' => 2],
    ['code' => 'CLP', 'name' => 'Chilean Peso', 'symbol' => '$', 'decimals' => 0],
    ['code' => 'CNY', 'name' => 'Chinese Yuan', 'symbol' => '¥', 'decimals' => 2],
    ['code' => 'COP', 'name' => 'Colombian Peso', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'CRC', 'name' => 'Costa Rican Colón', 'symbol' => '₡', 'decimals' => 2],
    ['code' => 'CVE', 'name' => 'Cape Verdean Escudo', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'CZK', 'name' => 'Czech Koruna', 'symbol' => 'Kč', 'decimals' => 2],
    ['code' => 'DJF', 'name' => 'Djiboutian Franc', 'symbol' => 'Fdj', 'decimals' => 0],
    ['code' => 'DKK', 'name' => 'Danish Krone', 'symbol' => 'kr', 'decimals' => 2],
    ['code' => 'DOP', 'name' => 'Dominican Peso', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'DZD', 'name' => 'Algerian Dinar', 'symbol' => 'د.ج', 'decimals' => 2],
    ['code' => 'EGP', 'name' => 'Egyptian Pound', 'symbol' => '£', 'decimals' => 2],
    ['code' => 'ETB', 'name' => 'Ethiopian Birr', 'symbol' => 'Br', 'decimals' => 2],
    ['code' => 'EUR', 'name' => 'Euro', 'symbol' => '€', 'decimals' => 2],
    ['code' => 'FJD', 'name' => 'Fijian Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'FKP', 'name' => 'Falkland Islands Pound', 'symbol' => '£', 'decimals' => 2],
    ['code' => 'GBP', 'name' => 'British Pound', 'symbol' => '£', 'decimals' => 2],
    ['code' => 'GEL', 'name' => 'Georgian Lari', 'symbol' => '₾', 'decimals' => 2],
    ['code' => 'GIP', 'name' => 'Gibraltar Pound', 'symbol' => '£', 'decimals' => 2],
    ['code' => 'GMD', 'name' => 'Gambian Dalasi', 'symbol' => 'D', 'decimals' => 2],
    ['code' => 'GNF', 'name' => 'Guinean Franc', 'symbol' => 'FG', 'decimals' => 0],
    ['code' => 'GTQ', 'name' => 'Guatemalan Quetzal', 'symbol' => 'Q', 'decimals' => 2],
    ['code' => 'GYD', 'name' => 'Guyanaese Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'HKD', 'name' => 'Hong Kong Dollar', 'symbol' => 'HK$', 'decimals' => 2],
    ['code' => 'HNL', 'name' => 'Honduran Lempira', 'symbol' => 'L', 'decimals' => 2],
    ['code' => 'HTG', 'name' => 'Haitian Gourde', 'symbol' => 'G', 'decimals' => 2],
    ['code' => 'HUF', 'name' => 'Hungarian Forint', 'symbol' => 'Ft', 'decimals' => 2],
    ['code' => 'IDR', 'name' => 'Indonesian Rupiah', 'symbol' => 'Rp', 'decimals' => 2],
    ['code' => 'ILS', 'name' => 'Israeli New Shekel', 'symbol' => '₪', 'decimals' => 2],
    ['code' => 'INR', 'name' => 'Indian Rupee', 'symbol' => '₹', 'decimals' => 2],
    ['code' => 'ISK', 'name' => 'Icelandic Króna', 'symbol' => 'kr', 'decimals' => 0],
    ['code' => 'JMD', 'name' => 'Jamaican Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'JPY', 'name' => 'Japanese Yen', 'symbol' => '¥', 'decimals' => 0],
    ['code' => 'KES', 'name' => 'Kenyan Shilling', 'symbol' => 'KSh', 'decimals' => 2],
    ['code' => 'KGS', 'name' => 'Kyrgystani Som', 'symbol' => 'с', 'decimals' => 2],
    ['code' => 'KHR', 'name' => 'Cambodian Riel', 'symbol' => '៛', 'decimals' => 2],
    ['code' => 'KMF', 'name' => 'Comorian Franc', 'symbol' => 'CF', 'decimals' => 0],
    ['code' => 'KRW', 'name' => 'South Korean Won', 'symbol' => '₩', 'decimals' => 0],
    ['code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'KZT', 'name' => 'Kazakhstani Tenge', 'symbol' => '₸', 'decimals' => 2],
    ['code' => 'LAK', 'name' => 'Laotian Kip', 'symbol' => '₭', 'decimals' => 2],
    ['code' => 'LBP', 'name' => 'Lebanese Pound', 'symbol' => 'ل.ل', 'decimals' => 2],
    ['code' => 'LKR', 'name' => 'Sri Lankan Rupee', 'symbol' => 'Rs', 'decimals' => 2],
    ['code' => 'LRD', 'name' => 'Liberian Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'LSL', 'name' => 'Lesotho Loti', 'symbol' => 'L', 'decimals' => 2],
    ['code' => 'MAD', 'name' => 'Moroccan Dirham', 'symbol' => 'د.م.', 'decimals' => 2],
    ['code' => 'MDL', 'name' => 'Moldovan Leu', 'symbol' => 'L', 'decimals' => 2],
    ['code' => 'MGA', 'name' => 'Malagasy Ariary', 'symbol' => 'Ar', 'decimals' => 2],
    ['code' => 'MKD', 'name' => 'Macedonian Denar', 'symbol' => 'ден', 'decimals' => 2],
    ['code' => 'MMK', 'name' => 'Myanmar Kyat', 'symbol' => 'K', 'decimals' => 2],
    ['code' => 'MNT', 'name' => 'Mongolian Tugrik', 'symbol' => '₮', 'decimals' => 2],
    ['code' => 'MOP', 'name' => 'Macanese Pataca', 'symbol' => 'MOP$', 'decimals' => 2],
    ['code' => 'MRO', 'name' => 'Mauritanian Ouguiya', 'symbol' => 'UM', 'decimals' => 2],
    ['code' => 'MUR', 'name' => 'Mauritian Rupee', 'symbol' => '₨', 'decimals' => 2],
    ['code' => 'MVR', 'name' => 'Maldivian Rufiyaa', 'symbol' => 'Rf', 'decimals' => 2],
    ['code' => 'MWK', 'name' => 'Malawian Kwacha', 'symbol' => 'MK', 'decimals' => 2],
    ['code' => 'MXN', 'name' => 'Mexican Peso', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'MYR', 'name' => 'Malaysian Ringgit', 'symbol' => 'RM', 'decimals' => 2],
    ['code' => 'MZN', 'name' => 'Mozambican Metical', 'symbol' => 'MT', 'decimals' => 2],
    ['code' => 'NAD', 'name' => 'Namibian Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'NGN', 'name' => 'Nigerian Naira', 'symbol' => '₦', 'decimals' => 2],
    ['code' => 'NIO', 'name' => 'Nicaraguan Córdoba', 'symbol' => 'C$', 'decimals' => 2],
    ['code' => 'NOK', 'name' => 'Norwegian Krone', 'symbol' => 'kr', 'decimals' => 2],
    ['code' => 'NPR', 'name' => 'Nepalese Rupee', 'symbol' => '₨', 'decimals' => 2],
    ['code' => 'NZD', 'name' => 'New Zealand Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'PAB', 'name' => 'Panamanian Balboa', 'symbol' => 'B/.', 'decimals' => 2],
    ['code' => 'PEN', 'name' => 'Peruvian Sol', 'symbol' => 'S/', 'decimals' => 2],
    ['code' => 'PGK', 'name' => 'Papua New Guinean Kina', 'symbol' => 'K', 'decimals' => 2],
    ['code' => 'PHP', 'name' => 'Philippine Peso', 'symbol' => '₱', 'decimals' => 2],
    ['code' => 'PKR', 'name' => 'Pakistani Rupee', 'symbol' => '₨', 'decimals' => 2],
    ['code' => 'PLN', 'name' => 'Polish Zloty', 'symbol' => 'zł', 'decimals' => 2],
    ['code' => 'PYG', 'name' => 'Paraguayan Guarani', 'symbol' => '₲', 'decimals' => 0],
    ['code' => 'QAR', 'name' => 'Qatari Riyal', 'symbol' => 'ر.ق', 'decimals' => 2],
    ['code' => 'RON', 'name' => 'Romanian Leu', 'symbol' => 'lei', 'decimals' => 2],
    ['code' => 'RSD', 'name' => 'Serbian Dinar', 'symbol' => 'дин.', 'decimals' => 2],
    ['code' => 'RUB', 'name' => 'Russian Ruble', 'symbol' => '₽', 'decimals' => 2],
    ['code' => 'RWF', 'name' => 'Rwandan Franc', 'symbol' => 'FRw', 'decimals' => 0],
    ['code' => 'SAR', 'name' => 'Saudi Riyal', 'symbol' => '﷼', 'decimals' => 2],
    ['code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'SCR', 'name' => 'Seychellois Rupee', 'symbol' => '₨', 'decimals' => 2],
    ['code' => 'SEK', 'name' => 'Swedish Krona', 'symbol' => 'kr', 'decimals' => 2],
    ['code' => 'SGD', 'name' => 'Singapore Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'SHP', 'name' => 'Saint Helena Pound', 'symbol' => '£', 'decimals' => 2],
    ['code' => 'SLE', 'name' => 'Sierra Leonean Leone', 'symbol' => 'Le', 'decimals' => 2],
    ['code' => 'SOS', 'name' => 'Somali Shilling', 'symbol' => 'S', 'decimals' => 2],
    ['code' => 'SRD', 'name' => 'Surinamese Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'STD', 'name' => 'São Tomé Príncipe Dobra', 'symbol' => 'Db', 'decimals' => 2],
    ['code' => 'SZL', 'name' => 'Swazi Lilangeni', 'symbol' => 'L', 'decimals' => 2],
    ['code' => 'THB', 'name' => 'Thai Baht', 'symbol' => '฿', 'decimals' => 2],
    ['code' => 'TJS', 'name' => 'Tajikistani Somoni', 'symbol' => 'SM', 'decimals' => 2],
    ['code' => 'TOP', 'name' => 'Tongan Paʻanga', 'symbol' => 'T$', 'decimals' => 2],
    ['code' => 'TRY', 'name' => 'Turkish Lira', 'symbol' => '₺', 'decimals' => 2],
    ['code' => 'TTD', 'name' => 'Trinidad Tobago Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'TWD', 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$', 'decimals' => 2],
    ['code' => 'TZS', 'name' => 'Tanzanian Shilling', 'symbol' => 'TSh', 'decimals' => 2],
    ['code' => 'UAH', 'name' => 'Ukrainian Hryvnia', 'symbol' => '₴', 'decimals' => 2],
    ['code' => 'UGX', 'name' => 'Ugandan Shilling', 'symbol' => 'USh', 'decimals' => 0],
    ['code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'UYU', 'name' => 'Uruguayan Peso', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'UZS', 'name' => 'Uzbekistan Som', 'symbol' => 'сўм', 'decimals' => 2],
    ['code' => 'VND', 'name' => 'Vietnamese Dong', 'symbol' => '₫', 'decimals' => 0],
    ['code' => 'VUV', 'name' => 'Vanuatu Vatu', 'symbol' => 'VT', 'decimals' => 0],
    ['code' => 'WST', 'name' => 'Samoan Tala', 'symbol' => 'T', 'decimals' => 2],
    ['code' => 'XAF', 'name' => 'Central African CFA Franc', 'symbol' => 'FCFA', 'decimals' => 0],
    ['code' => 'XCD', 'name' => 'East Caribbean Dollar', 'symbol' => '$', 'decimals' => 2],
    ['code' => 'XOF', 'name' => 'West African CFA Franc', 'symbol' => 'CFA', 'decimals' => 0],
    ['code' => 'XPF', 'name' => 'CFP Franc', 'symbol' => '₣', 'decimals' => 0],
    ['code' => 'YER', 'name' => 'Yemeni Rial', 'symbol' => '﷼', 'decimals' => 2],
    ['code' => 'ZAR', 'name' => 'South African Rand', 'symbol' => 'R', 'decimals' => 2],
    ['code' => 'ZMW', 'name' => 'Zambian Kwacha', 'symbol' => 'ZK', 'decimals' => 2]
];

$currencyList = [];
foreach ($currencies as $c) {
    $currencyList[] = [
        'code' => $c['code'],
        'name' => $c['name'],
        'symbol' => $c['symbol'],
        'decimal_places' => $c['decimals'],
        'symbol_position' => 'before'
    ];
}

$currenciesData = [
    'meta' => [
        'description' => 'All ' . count($currencyList) . ' Stripe-supported currencies',
        'source' => 'Stripe API',
        'last_updated' => date('Y-m-d')
    ],
    'currencies' => $currencyList
];

file_put_contents(__DIR__ . '/currencies.json', json_encode($currenciesData, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
echo "Created currencies.json with " . count($currencyList) . " currencies\n";
